# Nixpacks configuration for VitePress static site
# https://nixpacks.com/docs/configuration/file

providers = ["node"]

[variables]
NIXPACKS_NODE_VERSION = '22'

[phases.install]
onlyIncludeFiles = [
  "package.json",
  "pnpm-lock.yaml",
]

[phases.build]
cmds = ["pnpm run build"]

# Static site - VitePress output directory
[staticAssets]
directory = ".vitepress/dist"
